config/routes.rb
Tomatostats::Application.routes.draw do
  authenticated :user do
    root 'pomodoros#index', as: "authenticated_root"
  end

  root to: 'high_voltage/pages#show', id: 'about'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  as :user do
    get 'sign_in' => 'devise/sessions#new', :as => :new_session
    post 'sign_in' => 'devise/sessions#create', :as => :session
    match 'sign_out' => 'devise/sessions#destroy', :as => :destroy_session,
      :via => Devise.mappings[:user].sign_out_via
  end

  resources :pomodoros, only: :index do
    collection do
      post 'delete_multiple'
      post 'assign'
      post 'unassign'
    end
  end
  resources :imports, only: [:new, :create] do
    collection do
      get 'example_file'
    end
  end

  resources :projects

end

app/views/pages/about.html.haml
.jumbotron
  %h1 Beautiful stats for your pomodoros

  .row
    .col-md-6
      %p TomatoStats takes care of your pomodoros and display stats in a beautiful way! Sign in, import some pomodoros and check them out!
      %p
        Don't have any pomodoros? There's no need to be sad. Just
        = link_to "go grab some", example_file_imports_path
        and have fun!

    .col-md-6
      %p
        Currently we support data exported from
        = succeed "." do
          %a{href: "https://play.google.com/store/apps/details?id=net.phlam.android.clockworktomato"} Clockwork Tomato
        If you know any other pomodoro app that lets you export its data,
        = succeed "!" do
          %a{href: "https://github.com/ravicious/tomatostats/issues"} message us

  #screenshots.carousel.slide{data: { interval: 5000 }}
    %ol.carousel-indicators
      %li.active{data: { target: "#screenshots", 'slide-to' => 0 }}
      %li{data: { target: "#screenshots", 'slide-to' => 1 }}
      %li{data: { target: "#screenshots", 'slide-to' => 2 }}
      %li{data: { target: "#screenshots", 'slide-to' => 3 }}

    .carousel-inner
      .item.active
        = image_tag 'carousel/1.png'
        .carousel-caption
          %h3 Assign pomodoros to projects!
      .item
        = image_tag 'carousel/2.png'
        .carousel-caption
          %h3 Analyze our clean and helpful statistics!
      .item
        = image_tag 'carousel/3.png'
        .carousel-caption
          %h3 See your performance per week!
      .item
        = image_tag 'carousel/4.png'
        .carousel-caption
          %h3 Instantly toggle between pomodoros and hours view!

    %a.left.carousel-control{href: "#screenshots", data: { slide: 'prev' }}
      %span.icon-prev
    %a.right.carousel-control{href: "#screenshots", data: { slide: 'next' }}
      %span.icon-next
  :javascript
    $('#screenshots').carousel();