config/routes.rb
Tomatostats::Application.routes.draw do
  authenticated :user do
    root 'pomodoros#index', as: "authenticated_root"
  end

  root to: 'high_voltage/pages#show', id: 'about'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  as :user do
    get 'sign_in' => 'devise/sessions#new', :as => :new_session
    post 'sign_in' => 'devise/sessions#create', :as => :session
    match 'sign_out' => 'devise/sessions#destroy', :as => :destroy_session,
      :via => Devise.mappings[:user].sign_out_via
  end

  resources :pomodoros, only: :index do
    collection do
      post 'delete_multiple'
      post 'assign'
      post 'unassign'
    end
  end
  resources :imports, only: [:new, :create] do
    collection do
      get 'example_file'
    end
  end

  resources :projects

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :pomodoros, dependent: :nullify
  validates_presence_of :name, :user
  validates_uniqueness_of :name, scope: :user

  def to_s
    name
  end

  def self.sorted_by_name
    order("name ASC")
  end

  def self.sorted_by_activity
    reorder('updated_at DESC').limit(5)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  respond_to :html

  expose(:projects) { current_user.projects.sorted_by_name.includes(:pomodoros) }
  expose(:project, attributes: :project_params)
  expose(:stats) { project.pomodoros.stats }

  def show
    project.touch
  end

  def create
    if project.save
      flash[:success] = "Project #{project} added."
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    flash[:success] = "Project #{project} updated." if project.save
    respond_with project
  end

  def destroy
    flash[:success] = "Project #{project} deleted." if project.destroy
    respond_with project
  end

  private

  def project_params
    params.require(:project).permit(:name)
  end
end

app/views/projects/_calendar_overview.html.haml
.col-md-3
  .panel.panel-default
    .panel-heading Calendar overview
    .panel-body
      .tiny-calendar{data: { date: month.date + "-01" } }
        .events
          - month.weeks.each do |week|
            .event
              .start= week.days.first.date
              .end= week.days.last.date

app/views/projects/_form.html.haml
= simple_form_for project do |f|
  .row
    .col-lg-3
      = f.input :name
  = f.button :submit, class: 'btn btn-primary'

app/views/projects/_stats_panel.html.haml
.col-md-3
  .panel.panel-default
    .panel-heading= title
    .panel-body
      .progress
        .progress-bar{style: "width: #{(part_count.to_f / total_count)*100}%"}
      %p
        = pomodoros_count(part_count) + " done."
      %p.text-muted
        = surround '(', ')' do
          = number_to_percentage (part_count.to_f / total_count)*100, precision: 0
          = "of #{pomodoros_count(total_count)}".html_safe

app/views/projects/edit.html.haml
.panel.panel-default
  .panel-heading
    %h1.panel-title Edit Project
  .panel-body
    = render 'form'

app/views/projects/index.html.haml
.panel.panel-default
  .panel-heading
    %h1.panel-title Projects
  .panel-body
    %div.projects.list-group.col-md-5
      - projects.each do |project|
        = link_to project, class: 'list-group-item' do
          = project.name
          .badge= pluralize(project.pomodoros.size, "pomodoro") if project.pomodoros.any?

app/views/projects/new.html.haml
.panel.panel-default
  .panel-heading
    %h1.panel-title New Project
  .panel-body
    = render 'form'

app/views/projects/show.html.haml
#project.panel.panel-default
  .panel-body
    .page-header
      %h1
        = project.name
        %small
          = surround '(', ')' do
            = pomodoros_count stats.count
            in overall

    .btn-group
      = link_to glyph(:transfer) + "Toggle Views", '', class: 'btn btn-default', id: 'toggle_views'
      = link_to glyph(:pencil) + "Edit", edit_project_path(project), class: 'btn btn-default'
      = link_to glyph(:remove) + "Delete", project, method: :delete, class: 'btn btn-default', data: { confirm: "Are you sure?" }

    %h3 Monthly breakdown

    .row
      - stats.months.each do |month|
        = render 'stats_panel',
          title: Date.parse("#{month.date}-01").to_s(:month_and_year),
          part_count: month.count,
          total_count: stats.count

    %h3 Weekly breakdown

    - stats.months.each do |month|
      .panel.panel-default
        .panel-heading
          %h4.panel-title= Date.parse("#{month.date}-01").to_s(:month_and_year)
        .panel-body
          = render 'calendar_overview', month: month
          - month.weeks.each do |week|
            = render 'stats_panel',
              title: days_range(week.days.first.date, week.days.last.date),
              part_count: week.count,
              total_count: month.count