config/routes.rb
Tomatostats::Application.routes.draw do
  authenticated :user do
    root 'pomodoros#index', as: "authenticated_root"
  end

  root to: 'high_voltage/pages#show', id: 'about'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  as :user do
    get 'sign_in' => 'devise/sessions#new', :as => :new_session
    post 'sign_in' => 'devise/sessions#create', :as => :session
    match 'sign_out' => 'devise/sessions#destroy', :as => :destroy_session,
      :via => Devise.mappings[:user].sign_out_via
  end

  resources :pomodoros, only: :index do
    collection do
      post 'delete_multiple'
      post 'assign'
      post 'unassign'
    end
  end
  resources :imports, only: [:new, :create] do
    collection do
      get 'example_file'
    end
  end

  resources :projects

end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default
  .navbar-header
    %button{type: :button, class: 'navbar-toggle', data: { toggle: :collapse, target: '.navbar-ex1-collapse' }}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    = link_to "TomatoStats", root_path, class: 'navbar-brand'
  .collapse.navbar-collapse.navbar-ex1-collapse
    - if user_signed_in?
      %ul.nav.navbar-nav
        %li= link_to "Pomodoros", pomodoros_path
        %li= link_to "Import pomodoros", new_import_path
        %li.dropdown
          = link_to projects_path, class: 'dropdown-toggle', data: { toggle: 'dropdown' } do
            Projects
            %b.caret
          %ul.dropdown-menu.projects
            - current_user.projects.sorted_by_activity.each do |project|
              %li= link_to project, project
            %li.divider
            %li= link_to "All projects", projects_path
            %li= link_to "Add project", new_project_path

    %ul.nav.navbar-nav.navbar-right
      - if user_signed_in?
        %li.dropdown
          %a.dropdown-toggle{href: "#", data: { toggle: 'dropdown' }}
            = current_user
            %b.caret
          %ul.dropdown-menu
            %li= link_to "Sign out", destroy_session_path, method: :delete
      - else
        %li.dropdown
          %a.dropdown-toggle{href: "#", data: { toggle: 'dropdown'}}
            Sign in
            %b.caret
          %ul.dropdown-menu
            %li= link_to "with Google", user_omniauth_authorize_path(:google_oauth2)
            %li= link_to "with Facebook", user_omniauth_authorize_path(:facebook)

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "TomatoStats"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = stylesheet_link_tag "//cdnjs.cloudflare.com/ajax/libs/fullcalendar/1.6.4/fullcalendar.css"
    = javascript_include_tag "application"


  %body
    .container
      = render 'layouts/navbar'

      .row
        %div.col-md-12
          #flash-messages
            - flash.each do |key, value|
              %div{class: [flash_class(key), 'alert-dismissable']}
                %button.close{data: {dismiss: 'alert'}, aria: {hidden: true}} &times;
                = value
          = yield